site_name: Kosmach Mariia K3339 Web labs
nav:
  - "Home": index.md
  - "Лаборторная работа 1": 
    - Задание 1: LR1/task_1.md 
    - Задание 2: LR1/task_2.md
    - Задание 3: LR1/task_3.md
    - Задание 4: LR1/task_4.md
    - Задание 5: LR1/task_5.md
  - "Лабораторная работа 2": LR2/lab2.md
  - 3 lab:
    - "Практическая работа": pr/pr1.md
    - "Лабораторная работа": LR3/lab3.md

theme:
  name: material